singer-io/singer-python

- singer/__init__.py
- singer/requests.py
https://github.com/singer-io/singer-python/issues/11
> Add giveup function

- circle.yml
- setup.py
- singer/__init__.py
- singer/transform.py
- tests/test_transform.py
Adds a `transform` function to coerce data into the types specified in the schema.
> Add transform namespace

- setup.py
- singer/__init__.py
```python
>>> import singer
>>> from decimal import *
>>> m = singer.RecordMessage(stream='hello', record={'world': Decimal('0.11235')})
>>> singer.write_message(m)
{"record": {"world": 0.11235}, "type": "RECORD", "stream": "hello"}
```
> use simplejson to support decimals

- circle.yml
- setup.py
- singer/transform.py
- tests/test_transform.py
The error reporting in the transform module is lacking and this fixes that. In tackling that I fixed an issue where an additional field is silently ignored when it should report as an error.
> Update transform module

- circle.yml
- singer/__init__.py
- singer/logger.py
- singer/logging.py
- singer/messages.py
- singer/metrics.py
- singer/transform.py
- tests/test_transform.py
This reorders the module now that there's enough code that none should be in `__init__.py`.
> Reorder module layout

- singer/__init__.py
- singer/bookmarks.py
Introduces functions for easily manipulating states that make use of the standard `bookmarks` structure.
Also brings `write_message` function back to public API.
> Tooling for bookmark format

- setup.py
- singer/transform.py
- singer/utils.py
- tests/test_transform.py
> Fix for timezones

- singer/utils.py
like it says. also added a convenience now() fn
> strptime_with_tz will always return a tz aware datetime object

- singer/statediff.py
- tests/test_statediff.py
I'd like to make it easier to log messages showing the difference between two states, rather than the whole state. This supports that change. The main entry point is `statediff.diff`. Please see unit tests for examples of what that returns.
> Add functions for computing diff between two states

- singer/schema.py
it means the schema will accept anything within the object
> objects can have empty properties. 

- singer/schema.py
indicating any acceptance of anything
> items definitions may be empty maps

- singer/__init__.py
- singer/utils.py
Use this function to determine is a field should be synced.
> Adds should_sync_field to utils

- setup.py
- singer/messages.py
- tests/test_singer.py
1.parse time_extracted with faster ciso8601 lib. 
2. parse line json loads numbers as decimals
> parsing improvements

- setup.py
> Bump to v5.9.0

- CHANGELOG.md
- setup.py
Version bump for #138 
-  See #138 
- See #138 
- revert #138 and bump the version
> Bump to v5.10.0, update changelog

- singer/utils.py
This will cause each line to be prepended with `CRITICAL`
- 
- 
> Split the lines when logging the exception

- CHANGELOG.md
- setup.py
> Bump to v5.11.0

- CHANGELOG.md
- setup.py
> changed from version 5.11.0 to 5.12.0

- CHANGELOG.md
- setup.py
version bump to 5.12.1
- 
- low
> version bump to 5.12.1

- CHANGELOG.md
- setup.py
> Bump version 5.13.0

- CHANGELOG.md
- setup.py
- singer/schema_generation.py
- tests/test_catalog.py
- tests/test_exceptions.py
- tests/test_schema.py
- tests/test_schema_generation.py
- tests/test_transform.py
adds schema generation functionality
https://qlik-dev.atlassian.net/browse/SAC-28669
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> add json schema generation

- CHANGELOG.md
- setup.py
- singer/schema_generation.py
- singer/transform.py
- tests/test_transform.py
https://qlik-dev.atlassian.net/browse/SAC-28668
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> SAC-28668: fix transform and schema v5

- CHANGELOG.md
- setup.py
- singer/schema_generation.py
- singer/transform.py
- tests/test_transform.py
https://qlik-dev.atlassian.net/browse/SAC-28668
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> Sac 28668 fix transform and schema
