singer-io/singer-python

circle.yml
singer/__init__.py
tests/test_singer.py

As we start to add more targets, we'll want a common way to parse output from taps. This adds a `singer.parse_message` function that takes a JSON line and returns an object that represents the message.
* Add three new namedtuple classes to represent message data.
* RecordMessage
* SchemaMessage
* StateMessage
* Convert the write_record, write_schema, and write_state functions to use those classes.
* Add a parse_message function that takes a string and returns an instance of one of the message classes.
* Add unit tests

Add message representation

---

setup.py
singer/utils.py

Add two more args to the parse_args function. The function used to return a tuple of two args, (config, state). Now we just return the args object that is returned by argparse.
This is what we're using for tap-facebook.
I'll bump the major version before releasing, since this is a breaking change to parse_args.

Add --properties and --discover args

---

singer/utils.py

Remove load_schema and get_abs_path. load_schema('foo') is supposed to load the 'foo.json' file in the 'schema' directory. It does so by looking at the absolute path of __file__. In this case, that will be the absolute path of singer/utils.py, not the absolute path of the Tap that is calling this library fn. It doesn't make much sense for these functions to exist in this common library, and they've caused confusion for Tap authors.

Remove two fns

---

setup.py
singer/catalog.py
singer/schema.py
singer/utils.py
tests/test_catalog.py
tests/test_schema.py

Add object models for Schema and Catalog. See https://github.com/singer-io/tap-mysql/pull/15 for example usage.
* Add singer.schema. This contains a Schema class that represents a JSON Schema. If you're building a schema from scratch, you can use the constructor. If you're loading it from a file, you can use `Schema.load()`.
* Add singer.catalog. This contains a Catalog class. Usage is similar to `singer.schema.Schema`.
* Add a `--catalog` option to the command-line options defined in `singer.utils`. `singer.utils.parse_args` will now load a Catalog object automatically if the `--catalog` option is defined. I left the `--properties` option there but marked it as deprecated.

Add object models for Schema and Catalog

---

singer/__init__.py
tests/test_singer.py

We want to support for an experimental feature for versioning source data.
1. Add an optional `version` field to `RECORD` messages
2. Add an `ACTIVATE_VERSION` message.
The `version` field is the first field we have that's optional. This adds some complexity to the library, because so far all of the fields listed in the "attr list" are required, and many parts of the library depend on that being the case. I just went and changed the RecordMessage, SchemaMessage, and StateMessage classes to be plain old classes and not use or "attr list" thing. I decided to do that instead of use the `attrs` library that we use in some Taps because I'd like to keep the list of dependencies light in order to avoid potential dependency conflicts.
I added a unit test for the new stuff and verified that the …

Add version

---

circle.yml
singer/catalog.py
tests/test_catalog.py

Add `Catalog.get_stream(tap_stream_id)` for finding a stream by tap_stream_id.

Add get_stream

---

singer/transform.py

Adds a pre_hook argument that takes a callable to transform data before the _transform function is called. This is needed for `tap-adwords` and likely other taps in the future.

Adds pre_hook to transform function

---

setup.py
singer/__init__.py
singer/transform.py
tests/test_transform.py

Adds a recursive helper function for replacing JSON schema `$ref` data with the appropriate dict. 
Useful for JSON schemas that have a large amount of duplicated data and can benefit from a shared schema.

Adds functionality for resolving JSON schema refs

---

singer/transform.py
tests/test_transform.py

The Jira JSON schemas makes heavy use of "patternProperties." This JSON schema keyword is a regex that allows any properties matching the pattern.
This change modifies the code that resolves references so it handles these cases.

update resolving function to resolve refs for patternProperties

---

singer/transform.py

Modifies the recursive code to no longer raise an exception when the `"type"` key is missing from the schema. We can use a missing type to validate any JSON data.
> In addition, we also have the empty schema, that specifies all possible types of JSON documents.
-- https://cswr.github.io/JsonSchema/spec/multiple_types/

A missing 'type' key indicates any type so don't transform

---

singer/transform.py
tests/test_transform.py

I am running into an issue because I have a scenario where a given key can be either a string or an object. The transform function failed because of this - when the data was a string instead of an object, the ".items()" function fails.

Fix transformation when schema has multiple types

---

singer/schema.py

tap-mysql is the only tap relying on `sqlDatatype` being part of the schema, and I'm removing that in https://github.com/singer-io/tap-mysql/pull/44, so we should also remove it here.

sqlDatatype no longer part of schema

---

singer/utils.py
tests/test_utils.py

Currently if you have a date-time where the year is < 1000 then the `strftime` function will not pad zeros to the left of the date. This fixes that.

Fix formatting of dates when they are < 1000

---

singer/schema.py
tests/test_schema.py

The Schema class doesn't support the `additionalProperties` key which means this property is not printed during discovery. This is causing an issue in the linter I am working on https://github.com/b-ryan/singer-best-practices-linter

Add additionalProperties support to Schema

---

singer/messages.py

Not all taps use the `write_schema` function. It is more appropriate to handle the `bookmark_properties` initialization within the `SchemaMessage` constructor itself.

move bookmark property handling from write_schema into SchemaMessage __init__

---

singer/messages.py

Fixed bug where the initializer for SchemaMessage was forcing the passed argument 'bookmark_properties' to be a list rather than forcing it's attribute 'self.bookmark_properties' to be a list.

Changing SchemaMessage so that bookmark_properties is always a list

---

singer/catalog.py
tests/test_catalog.py

`stream_alias` is a property on `CatalogEntry` but does not currently get dumped out in `to_dict`.
`test_catalog` updated to test for cases where stream_alias is included and excluded.

Add stream_alias to Catalog.to_dict

---

.gitignore
singer/catalog.py
tests/test_catalog.py

`metadata` is a property on `CatalogEntry` but is not passed along from `Catalog` creation when using `from_dict()`.
`test_catalog` updated to test for cases where `metadata` is included and excluded.

Add metadata assignment to Catalog.from_dict

---

singer/utils.py
tests/test_utils.py

In response to this issue [#59](https://github.com/singer-io/singer-python/issues/59)
Some C Libraries version of strftime() recognize a field width modifier in the format string, e.g. the ```04``` in ```%04Y-%m-%dT%H:%M:%S.%fZ``` which specifies the width of the year field.  
We added this ```04``` to our date format to ensure that dates with years < 1000 still have a 4 digit year.
However, other C Libraries do not recognize this field width modifier, but zero pad dates with years < 1000 to ensure they are 4 digits long.  
To remedy this inconsistency, the ```04``` is being removed from the date format string, and an optional argument is being added to singer.utils.strftime() so callers of that function can supply their own date format string.

changing strftime format string

---

singer/utils.py
tests/test_utils.py

I figured this decorator could come in handy. Every tap has code like:
```python
def main_impl():
....
def main():
try:
main_impl()
except ...
LOGGER.critical....
```
Using this decorator would allow just doing this:
```python
@handle_top_exception(LOGGER)
def main():
....
```

Decorator for wrapping main functions with critical log

---

CONTRIBUTING.md
Makefile
README.md
bin/circle_deps
bin/circle_test
circle.yml
setup.py
singer/messages.py
singer/schema.py
singer/utils.py

Motivation
----------
Because the parser is built and then immediately used it is not open for
extension. This allows taps to get the parser and then extend it with
their own options.
Prior behavior is preserved through the use of an optional parser arg to
the utils.parse_args function.
Also adds a CONTRIBUTING document and aligns circle build with dev.

Provide get_default_args_parser

---

setup.py
singer/messages.py
singer/transform.py
singer/utils.py
tests/test_transform.py

The transformer requires datetime strings to be pegged at UTC, or it fails. This causes datetime strings with timezones to fail, since they have a time zone attached and aren't being shifted.
This adds a function to utils that tries to parse and peg at UTC before passing into `strftime` and uses it within `string_to_datetime` in `transform.py`.

Parse to UTC for datetime transform

---

singer/utils.py

Fix https://github.com/singer-io/singer-python/issues/86
Update `strftime` to fallback to non-`%04Y` formatting on Windows 10
The current tests are sufficient to fail before on Windows and pass after this patch, `nosetests tests/test_utils.py`

Update strftime to fallback to non %04Y formatting on Windows

---

README.md

The example code in the README doesn't match the function signature for `write_schema()`

Add key property to function call, clean up whitespace

---

singer/schema.py
singer/transform.py
tests/test_transform.py

JSON Schema supports object schemas having the keys `additionalProperties` and `patternProperties` described in the Draft 4 validation document [here](https://tools.ietf.org/html/draft-fge-json-schema-validation-00).
- Empty object schemas still validate against anything
PatternProperties are a JSON object of the form `{"regex_pattern": {...schema...}}`. For example, a simple "catch-all" schema would look like this:
```
{
"type": "object",
"patternProperties": {
".+": {},
...
}
}
```
This is useful in the event that you want the schema to validate against all keys, but override using `properties` for more specific types (like date-times).
**Principles**
- `properties` takes precedence
- An empty `properties` and `patternProperties` is treated as an empty schema and validates against all
- …

Support pattern properties in object schemas

---

singer/utils.py

Currently, `parse_args` overwrites `config` and other parsed arguments, a file path, with the parsed JSON. This makes the original file path inaccessible. This PR adds allows for accessing the original argument / file path.
For context, for a tap which needs the refresh token saved after each auth, I need to save the changes to the config file, which means I need access to the config path.
Functional Testing
- Running `parse_args` the args for a tap and accessing the `config_path`

Retain Argument Paths

---

singer/statediff.py
singer/transform.py

Do not output raw data to logs when a SchemaMismatch error occurs in the transformer.
- Ran a tap which outputs a record that violates the JSON Schema. Observed the appropriate output 
- A little bit harder to diagnose a bug where a record violates its JSON Schema data type(s).
To observe the old behavior, modify [logging.conf](https://github.com/singer-io/singer-python/blob/master/singer/logging.conf#L11) to `DEBUG` and the output display the raw record.

Updates transform logging to only output the raw data in DEBUG

---

Makefile
singer/transform.py
tests/test_transform.py

This is an extension of PR #94. I have added two tests, one which tests that nested fields in an object are filtered and one which tests that nested fields in an array of objects are filtered.
- Wrote new tests which pass
- Should not be any breaking changes as all previous tests pass unaltered.

Filter nested properties based on metadata

---

CHANGELOG.md
setup.py

Bumping version for release of #130 
- N/A
- Low, accounted for in #130 
- revert #130 and bump patch version again

Version 5.9.1 and changelog

---

singer/metadata.py
tests/test_metadata.py

* Add docs
* use unittest methods to do asserts
* adds a missing test
* update expected values
This duplicates changes in #132, but I added the doc string to explain the rational behind the test, and the `self.subTest()` context manager to make the process of examining a failing test more sane.
Example test run:
```
$ python -m unittest tests/test_metadata.py
..
======================================================================
FAIL: test_standard_metadata (tests.test_metadata.TestStandardMetadata) (test_number=10)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/code/singer-python/tests/test_metadata.py", line 321, in test_standard_metadata
self.assertDictEqual(expected_value, actual_value)
AssertionError: {(): …
```

Fix tests for get_standard_metadata

---

.circleci/config.yml
singer/__init__.py
singer/exceptions.py
tests/test_exceptions.py

This PR adds base exception classes for taps to use.
- Added and ran unit tests
- I want to be conservative about what makes it into this file this early. I want to avoid cluttering the namespace with classes that turn out to be specific to just a few taps

Add exceptions

---

setup.py
singer/transform.py
tests/test_transform.py

This PR introduces a new concept: A Singer custom string format type that specifies a decimal value.
The reasoning behind this is to maintain decimal precision throughout ELT pipelines by converting to and from JSON strings and parsing with `decimal.Decimal` (in Python).
- None, will write automated unittests to exercise this function.
- Low, this is an additive feature.

Add support for custom decimal string formatter

---

singer/transform.py
tests/test_transform.py

Removed the normalize function from singer.decimal code in the transformer to avoid excessive scientific notation. We also updated the tests.
- ran nosetests
- low

removed normalize() from singer.decimal to avoid excessive scientific notation

---

CHANGELOG.md
setup.py

Update `pytz` version to >=2018.4
- 
- 

remove pinned `pytz` version

---

singer/utils.py

This implementation adds support to parse dev mode arguments `-D` or `--dev` in cmdline.
- Manually updated tap singer-python library and from orchestrator tested the discovery with `-D` and `--dev` on an existing connection.
- 

parse dev mode argument

---

.circleci/config.yml
CHANGELOG.md
setup.py
singer/catalog.py
singer/exceptions.py
singer/messages.py
singer/transform.py
singer/utils.py

Bumps backoff from `1.8.0` to `2.2.1`. In the new major version backoff drops support for [python 3.5, but adds it for 3.10+ ](https://github.com/litl/backoff/blob/master/CHANGELOG.md#v200---2022-04-26). 
This is a major version bump, since taps running python 3.5 will no longer work.
Updates circle config to be compatible with newer python versions, and pylint updates. 
- Tested locally with tap-mixpanel
- Taps running on python 3.5 will not be able to use this version

Bump backoff to be compatible with newer python versions

---

CHANGELOG.md
setup.py

Pin simplejson and backoff to _only_ their major versions
- Verified extraction succeeds with tap using `singer-python` as dependency
- Low. Pinning dependencies to a major version should not cause breaking changes.

Relax dependency version requirements

---

CHANGELOG.md
setup.py
singer/messages.py
tests/test_singer.py

This PR introduces a dynamic setting for the ensure_ascii parameter in the `json.dumps` function, with its default value set to `True`. This change allows for greater flexibility in JSON serialization, enabling non-ASCII characters to be preserved when needed by explicitly passing `ensure_ascii=False`.
- Unit Tests: Added and updated unit tests to verify the correct behaviour of JSON serialization with both ensure_ascii=True (default) and ensure_ascii=False.
- Alpha: Performed PR-alpha on the customer connection to test JSON serialization for the special characters
- If not ensure_ascii is set differently per the expectations within the tap code, then customers can experience the data discrepancy.

Make `ensure_ascii` Dynamic with Default Set to `True` in JSON Serialization
